language: node_js
node_js:
  - 8
branches:
  only:
    - master
script:
  - npm test
install:
  - npm install
after_success:
  - npm run coveralls
  
secure: "WwQmpxICGA/ZarFHmPACero2idRxBMkJpbTPO/4uL3wkCbO3y2SouuV5zPCntYRVHQ3zDrfBRL++72193a+te0Leu5LDu77gbBWjzfEY5MATpWrJ03LVZPvZfVLrDf6GrqimX7J6BEuYeFYhq6c9l5jI+Wt3S8IwIXnc4b514VnxEDmfeTWmJ0XRVh24ZYtcIyypi91ZsIy5Hat9BTNuqofa7V4uNGSAhYRB8U8VmonsAOIrak4vjcsfdUeLOd6hzMKDVIwPsnzTzkblmu+mt+LM8PXCb4JOKmkWjGU30xG9WbDHBiSTBQgGVLrGlzLuKeSHFVnajiL+nO95mzgL+G5c3MZ6q0EzrrO+P+tQkBAsMXH98YH9+qgSpDGZwNNQ/e4085qu6zM1x7Mi8cof/suYCAY/Eh+02ajRaLrAQ/qB7R0Evr3xxQ3XcQ67tUpOYBIOYRTeqZakwX2g2JXBhvNfnZ/Iv213iJmYNKbWFEt0WOxFad+7gR9SZLXx1Gd6QduYsVm9upXuThniz/ccCIlS/3PwyCaA4fsrQUhC3AU1uDtIUddR5pR4VjfcuwdEx1TW9qQYDvkubt1Fe9owkpn0N7y97EwC7BTJtlP9XmjJJ6KIuaH5n3UgNeWCEi+HvDcW1n1qmbnYUUN0fevNCTBNTwYBuYncE/cfSJPLjhA="
